# Generated by Django 5.1 on 2024-09-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChartData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value1", models.IntegerField()),
                ("value2", models.IntegerField()),
                ("value3", models.IntegerField()),
            ],
        ),
    ]
